pool:
   vmImage: 'ubuntu-18.04'

jobs:
  - job: nodejsGM
    steps:
      - checkout: self
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: Install Node.js
      - script: npm install
      - script: npm test
        displayName: Test