pool:
  vmImage: 'ubuntu-18.04'

strategy:
  matrix:
    LTS:
      versionSpec: '12.x'
    latest:
      versionSpec: '14.x'

steps:
  - checkout: self
  - task: NodeTool@0
    inputs:
      versionSpec: $(versionSpec)
    displayName: Install Node.js
  - script: npm install
  - script: npm test
    displayName: Test